main: com.SirBlobman.blobcatraz.Blobcatraz
name: Blobcatraz
version: 0.0.0.16
author: SirBlobman
description: Plugin used for nearly everything in the Blobcatraz server. 
softdepend: [Votifier, HolographicDisplays, LampControl]
commands:
  blobcatraz:
    description: Command [] = Argument <> = Optional
    usage: /blobcatraz [give|enchant|reload] [item name|enchant name] [enchant level]
    permission: blobcatraz.blobcatraz
    permission-message: You don't have the permission "blobcatraz.blobcatraz"
  afk:
    description: Away From Keyboard
    usage: /afk <reason>
    permission: blobcatraz.afk
    permission-message: You don't have the permission "blobcatraz.afk"
  findorigin:
    description: Makes a hologram at the origin (requires HolographicDisplays)
    usage: /findorigin
    permission: blobcatraz.find.origin
    permission-message: You don't have the permission "blobcatraz.find.origin"
  portal:
    description: Creates a portal/Gets portal wand/Creates command portal
    permission: blobcatraz.portal
    usage: /portal wand OR /portal create <name> OR /portal create <name> <command without /> OR /portal list OR /portal remove <name>
    permission-message: You don't have the permission "blobcatraz.portal" 
  rename:
    description: Renamed the currently held item
    usage: /rename [new name]
    permission: blobcatraz.rename
    permission-message: You don't have the permission "blobcatraz.rename"
  random:
    description: Generates a random number ranging from 0 to 32767
    usage: /random <min> <max>
    permission: blobcatraz.random
    permission-message: You can't generate random numbers! You don't have the permission "blobcatraz.random"
  chat:
    description: Allows you to mess with chat. You can turn it on, off, and clear it
    usage: /chat [on/off/clear/status]
    permission: blobcatraz.chat
    permission-message: You don't have permission to mess with chat. You need "blobcatraz.chat"
  setmotd:
    description: Changes the MOTD
    usage: /setmotd [new motd]
    permission: blobcatraz.set.motd
  vote:
    description: Shows you all the vote links specified from the config
    usage: /vote
  addlore:
    description: Adds lore to an item that already has lore
    usage: /addlore [Lore]
    permission: blobcatraz.setlore
  setlore:
    description: Sets the item lore (deletes old lore)
    usage: /setlore [Lore]
    permission: blobcatraz.setlore
  resetitem:
    description: Clears any metadata that the item has. Includes Lore, Name, and Enchants
    usage: /resetitem
    permission: blobcatraz.resetitem
  repair:
    description: Fixes an item (its like an anvil)
    usage: /repair
    permission: blobcatraz.repair