main: com.SirBlobman.blobcatraz.Blobcatraz
name: Blobcatraz
version: 0.0.1.12
author: SirBlobman
description: Plugin used for nearly everything in the Blobcatraz server. 
softdepend: [Vault, HolographicDisplays, Votifier]
load: POSTWORLD
commands:
  blobcatraz:
    description: Command [] = Argument <> = Optional
    usage: /blobcatraz [give|enchant|reload|restart] [item name|enchant name] [enchant level]
    permission: blobcatraz.blobcatraz
    permission-message: You don't have the permission "blobcatraz.blobcatraz"
  afk:
    description: Away From Keyboard
    usage: /afk <reason>
    permission: blobcatraz.afk
    permission-message: You don't have the permission "blobcatraz.afk"
  findorigin:
    description: Makes a hologram at the origin (requires HolographicDisplays)
    usage: /findorigin
    permission: blobcatraz.find.origin
    permission-message: You don't have the permission "blobcatraz.find.origin"
  portal:
    description: Creates a portal/Gets portal wand/Creates command portal
    permission: blobcatraz.portal
    usage: /portal wand OR /portal create <name> OR /portal create <name> <command without /> OR /portal list OR /portal remove <name>
    permission-message: You don't have the permission "blobcatraz.portal" 
  rename:
    description: Renamed the currently held item
    usage: /rename [new name]
    permission: blobcatraz.rename
    permission-message: You don't have the permission "blobcatraz.rename"
  random:
    description: Generates a random number ranging from 0 to 32767
    usage: /random <min> <max>
    permission: blobcatraz.random
    permission-message: You can't generate random numbers! You don't have the permission "blobcatraz.random"
  chat:
    description: Allows you to mess with chat. You can turn it on, off, and clear it
    usage: /chat [on/off/clear/status]
    permission: blobcatraz.chat
    permission-message: You don't have permission to mess with chat. You need "blobcatraz.chat"
  setmotd:
    description: Changes the MOTD
    usage: /setmotd [new motd]
    permission: blobcatraz.set.motd
  vote:
    description: Shows you all the vote links specified from the config
    usage: /vote
  addlore:
    description: Adds lore to an item that already has lore
    usage: /addlore [Lore]
    permission: blobcatraz.setlore
  setlore:
    description: Sets the item lore (deletes old lore)
    usage: /setlore [Lore]
    permission: blobcatraz.setlore
  removelore:
    description: Removes the lore of an item (or a line of lore)
    usage: /removelore <line>
    permission: blobcatraz.removelore
    aliases: [dellore]
  resetitem:
    description: Clears any metadata that the item has. Includes Lore, Name, and Enchants
    usage: /resetitem
    permission: blobcatraz.resetitem
  repair:
    description: Fixes an item (its like an anvil)
    usage: /repair
    permission: blobcatraz.repair
    aliases: [fix]
  balance:
    description: Gets the balance of yourself or another player
    usage: /balance <Player>
    permission: blobcatraz.economy.balance
    aliases: [bal, money]
  item:
    description: Gives you items without NBT data
    usage: /item [item] [amount] [damage] OR /item list
    permission: blobcatraz.items.give
    aliases: [i, selfgive]
  unban:
    description: Removes the ban status of a player
    usage: /unban [player]
    permission: blobcatraz.unban
    aliases: [pardon]
  ban:
    description: Permanently ban a player
    usage: /ban [player] [reason]
    permission: blobcatraz.ban
    aliases: [banish, exile]
  economy:
    description: Manage the server economy
    usage: /economy [set|give|take|reset|clearall] <player> <amount>
    permission: blobcatraz.economy.manage
    aliases: [eco]
  fly:
    description: Check or toggle your flight
    usage: /fly <on|off>
    permission: blobcatraz.fly
    aliases: [soar]
  worth:
    description: Check the value of an item
    usage: /worth <item> <amount>
    permission: blobcatraz.worth
  setworth:
    description: Set the sell value of an item
    usage: /setworth <item> [amount]
  randomtp:
    description: Teleport to a random location
    usage: /randomtp <tp | gui>
    permission: blobcatraz.randomtp
    aliases: [rtp]
  heal:
    description: Heal yourself or another player
    usage: /heal <player>
    permission: blobcatraz.heal
  tempban:
    description: Temporarily ban a player
    usage: /tempban [player] [time[s|m|h|d|w|y|c]] [reason]
  spawn:
    description: Teleport to the server spawn
    usage: /spawn
  setspawn:
    description: Set the spawn of the server
    usage: /setspawn
  freeze:
    description: Freeze a player that is misbehaving
    usage: /freeze [player]
  unfreeze:
    description: Unfreeze a player that has been good
    usage: /unfreeze [player]
  btime:
    description: Get the server time
    usage: /time [12 | 24]
  date:
    description: Get the server date
    usage: /date
  pluginmanager:
    description: Manage server plugins
    usage: /pluginmanager [load|unload|reload|sreload|enable|disable|show|list] [plugin name (without.jar)]
    aliases: [pm, plm, plugman]
  enchant: 
    description: Enchant an item with any level (up to 32767)
    usage: /enchant [enchantment] [level]
    aliases: [ench]
  gamemode:
    description: Change your gamemode (Survival, Creatie, Adventure, Spectator)
    usage: /gamemode [s|c|a|sp] <player>
    aliases: [gm, gms, gmc, gma, gmsp]
  unbreakable:
    description: Make one of your items unbreakable (non-enchant, Only works on SPIGOT-based builds)
    usage: /unbreakable
  clearinventory:
    description: Clear an inventory
    usage: /clearinventory <player> <enderchest|armor|inventory> <item>
    aliases: [ci, clear]
  baltop:
    description: Get the top 10 players based on amount of $
    usage: /baltop
    aliases: [balancetop]
  tell:
    description: Send a message to a Player
    usage: /tell [player] [message]
    aliases: [msg]
  reply:
    description: Reply to someone who msged you
    usage: /r [message]
    aliases: [r]
  commandspy:
    description: Toggle your ability to spy on everyone's commands!
    usage: /commandspy
    aliases: [spy]
  vanish:
    description: Toggle your visibility
    usage: /vanish
    aliases: [v]  
  disco:
    description: Disco!!!
    usage: /disco [off|glass|armor|wool|carpet|clay|banner]
  tag:
    description: Change your name in the Player List. Cannot be more than 16 characters.
    usage: /tag <name>
  hub:
    description: Teleport to the Hub
    usage: /hub
  sethub:
    description: Change where the hub is located
    usage: /sethub
  warp:
    description: Warp to a defined warp
    usage: /warp [name]
  setwarp:
    description: Set the location to a warp
    usage: /setwarp [name]
  delwarp: 
    description: Delete a warp that you have set
    usage: /delwarp [name]
  teleport:
    description: Teleport to a Player or to Coordinates
    usage: /teleport [player] OR /teleport [x] [y] [z] OR /teleport [player] [player]
    aliases: [tp]
  center:
    description: Go to the center of a Block
    usage: /center
    aliases: [centre]
  home:
    description: Teleport to your home
    usage: /home [name]
  sethome:
    description: Set the location for your home
    usage: /sethome [name]
  delhome:
    description: Delete your home
    usage: /delhome [name]
  withdraw:
    description: Take some money from your account
    usage: /withdraw [amount]
  autopickup:
    description: Toggle your ability to auto pickup mined blocks
    usage: /autopickup
  feed:
    description: No more hunger!
    usage: /feed <player>
  kit:
    description: Give yourself a kit from the list
    usage: /kit [name]
  createkit:
    description: Create a new kit from your inventory
    usage: /createkit [name]
  deletekit: 
    description: Delete a kit
    usage: /delekit [name]
  recipe:
    description: Show the recipe for an item
    usage: /recipe [item] <page>
    aliases: [formula]
  KitToChest:
    description: Put a kit into a chest
    usage: /KitToChest [kit]
  ChestToKit:
    description: Turn a chest's inventory into a kit
    usage: /ChestToKit [kit name]
  tshop:
    description: Open the token shop GUI
    usage: /tshop
    aliases: [tokenshop]