name: Blobcatraz
version: 0.2.0
description: Main plugin for the Blobcatraz server
load: POSTWORLD
author: SirBlobman
authors: [SirBlobman, ToonBasic]
website: http://blobcatraz.mc-srv.com
main: com.SirBlobman.blobcatraz.Blobcatraz
database: false
depend: []