name: Blobcatraz
version: 0.2.0
description: Main plugin for the Blobcatraz server
load: POSTWORLD
author: SirBlobman
authors: [SirBlobman]
website: http://sirblobman.ddns.net
main: com.SirBlobman.blobcatraz.Blobcatraz
database: false
depend: []